/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElC: typeof import('element-plus/es')['ElC']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCo: typeof import('element-plus/es')['ElCo']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSc: typeof import('element-plus/es')['ElSc']
    ElScr: typeof import('element-plus/es')['ElScr']
    ElScroll: typeof import('element-plus/es')['ElScroll']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTe: typeof import('element-plus/es')['ElTe']
    ElText: typeof import('element-plus/es')['ElText']
    IngameLayout: typeof import('./src/components/layouts/ingame-layout/IngameLayout.vue')['default']
    PlayerCard: typeof import('./src/components/players/player-card/PlayerCard.vue')['default']
    PlayersBar: typeof import('./src/components/players/players-bar/PlayersBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
